import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import Styles from "../styles/Home.module.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import { Container, Nav, NavDropdown, Navbar } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowRightLong,
  faQuoteLeft,
  faQuoteRight,
  faAt,
  faPhone,
  faBars,
  faBus,
  faGraduationCap,
  faChalkboardUser,
} from "@fortawesome/free-solid-svg-icons";

const Navigationbar = () => {
  return (
    <>
    <Head>
        <title>NavBar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous"
        /> */}
      </Head>

      <div class="m-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary p-4" id="nav">
          <div class="container-fluid">
            <a href="#" class="navbar-brand">
              Genisis School
            </a>
            <button
              type="button"
              class="navbar-toggler"
              data-bs-toggle="collapse"
              data-bs-target="#navbarCollapse"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <div class="navbar-nav ms-auto" id="nav-link">
              <a href="../pages/Main/Home" class="nav-item nav-link active">
                  Home
                </a>
                <a href="#" class="nav-item nav-link">
                  Profile
                </a>
                <a href="#" class="nav-item nav-link">
                  Messages
                </a>
                <a href="#" class="nav-item nav-link" tabindex="-1">
                  Reports
                </a>
                <a href="#" class="nav-item nav-link">
                  Login
                </a>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"
      />
    </>
  );
};

export default Navigationbar;
